sudo: required
sudo: true
dist: xenial

addons:
  firefox: "46.0"
  chrome: "stable"

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - chmod +x .upload_reports.sh

services:
  - xvfb

install:
  - pip install pipenv

script:
  - pipenv install --dev
  - pipenv graph
  - pipenv run py.test -sv --cov-config .coveragerc --cov-report html:skip-covered --cov-report term:skip-covered --cov=selene --tb=short tests/
  - codecov

after_script:
  - "./.upload_reports.sh"