addons:
  firefox: "46.0"

language: python
python:
  - "2.7"

install:
  - "pip install -r requirements.txt"

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

script:
  - "pytest -sv tests/"